### ISSUE TITLE
Aria link icon not found

### ISSUE THREAD

**Issue by Amain** [lefred/mailspring-libre-aria#2]
After installing (git clone) plugin into ~/.config/Mailspring/packages/mailspring-libre-aria the plugin works, but fails to load the link icon:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND 
/usr/share/mailspring/resources/app.asar/src/flux/stores/database-store.js:137 
oracle.png:1

```
_Thanks for sharing this plugin!_

**Comment by Amain** [comment]
Ahh,
```
$ cd ~/.config/Mailspring/packages/
$ mv mailspring-libre-aria aria
```
...does the trick.

**Comment by lefred** [comment]
If you install the plugin from Mailspring itself, it will call it like that ;)
